In [ ]:
import numpy as np

In [ ]:
x=1 #Iniciar ciclo while

while x==1:
  renglonesA = int(input("Cantidad de renglones matriz A: \n "))
  columnasA = int(input("Cantidad de columnas matriz A: \n "))

  A = np.zeros((renglonesA,columnasA)) #Iniciar arreglo vacio

  print("Ingresa los elementos de A:\n ")

  for i in range(renglonesA):
    for j in range(columnasA):
      A[i][j] = float(input("Elemento {0}{1}: \n".format(i+1,j+1)))


  print("Tu matriz A es: \n")
  print(A)

  renglonesB = int(input("Cantidad de renglones matriz B: \n"))
  columnasB = int(input("Cantidad de columnas matriz B: \n "))

  B= np.zeros((renglonesB,columnasB))
  for i in range(renglonesB):
    for j in range(columnasB):
      B[i][j] = float(input("Elemento {0}{1}: \n".format(i+1,j+1)))

  print("Tu matriz B es: \n")
  print(B)

  op = int(input("Escribe la operación (1 = suma de matrices, 2 = matriz por escalar) :\n "))

  if op == 1:
    if A.shape == B.shape:
      C= A+B
      print("La matriz resultante es:\n ")
      print(C)
    else:
      print("El numero de renglones y columnas no coinciden, no se pueden sumar\n")

  elif op == 2:
    escalar = float(input("Introduce el escalar: \n"))

    matriz = int(input("Multiplicar por matriz A o B? (1=A, 2=B): \n "))

    if matriz == 1:
      A = escalar*A

      print("Tu matriz A es: \n")
      print(A)

    elif matriz == 2:
      B = escalar*B

      print("Tu matriz B es: \n")
      print(B)
  
    else: 
      print("operación no reconocida")

  else:
    print("operación no reconocida")

  x=int(input("Introducir más matrices? (0=NO, 1=sí) :")) #iniciar de nuevo todo 



Cantidad de renglones matriz A: 
 2
Cantidad de columnas matriz A: 
 2
Ingresa los elementos de A:
 
Elemento 11: 
2
Elemento 12: 
2
Elemento 21: 
2
Elemento 22: 
2
Tu matriz A es: 

[[2. 2.]
 [2. 2.]]
Cantidad de renglones matriz B: 
2
Cantidad de columnas matriz B: 
 2
Elemento 11: 
2
Elemento 12: 
2
Elemento 21: 
2
Elemento 22: 
2
Tu matriz B es: 

[[2. 2.]
 [2. 2.]]
Escribe la operación (1 = suma de matrices, 2 = matriz por escalar) :
 1
La matriz resultante es:
 
[[4. 4.]
 [4. 4.]]
Introducir nuevas matrices? (0=NO, 1=sí) :1
Cantidad de renglones matriz A: 
 2
Cantidad de columnas matriz A: 
 2
Ingresa los elementos de A:
 
Elemento 11: 
2
Elemento 12: 
2
Elemento 21: 
2
Elemento 22: 
2
Tu matriz A es: 

[[2. 2.]
 [2. 2.]]
Cantidad de renglones matriz B: 
2
Cantidad de columnas matriz B: 
 2
Elemento 11: 
2
Elemento 12: 
2
Elemento 21: 
2
Elemento 22: 
2
Tu matriz B es: 

[[2. 2.]
 [2. 2.]]
Escribe la operación (1 = suma de matrices, 2 = matriz por escalar) :
 1
La matriz resultan